export const products = {
  Broasted: [
    {
      code: 999,
      indexInCategory: 99,
      _id: "62169d7d7bb2816b74a76728",
      category: "Broasted",
      modifierGroups: [
        {
          description: "Select you favouriste source",
          printName: "",
          modifiers: [
            { description: "Hot creepo sauce", price: "10" },
            { description: "Tin snow sauce", price: "20" },
          ],
        },
      ],
      printName: "",
      popular: false,
      video: "",
      archived: false,
      price: 120,
      onSale: true,
      isAvailable: true,
      image:
        "https://media.istockphoto.com/photos/plate-of-delectable-golden-brown-crispy-fried-chickens-on-wooden-picture-id1297771706?s=612x612",
      description: "sdfdfhowrman flavoured with chcobar tasky blendy",
      name: "Kippi koo Chocolator Amuco shawarmo",
      __v: 0,
    },
    {
      code: 999,
      indexInCategory: 99,
      _id: "6216a1c67bb2816b74a7672e",
      category: "Broasted",
      modifierGroups: [
        {
          description: "Select Sprinkle powder of your linkin",
          printName: "",
          modifiers: [
            { description: "Red wine powder", price: "10" },
            { description: "Blue coil powder", price: "15" },
          ],
        },
        {
          description: "Select you favouriste toppings",
          printName: "",
          modifiers: [
            { description: "Chilli flakes", price: "10" },
            { description: "Orange burned pieces", price: "8" },
          ],
        },
      ],
      printName: "",
      popular: false,
      video: "",
      archived: false,
      price: 440,
      onSale: true,
      isAvailable: true,
      image: null,
      description: "beautify hot pieces of thist and that",
      name: "4 Pc Broasted chicken",
      __v: 0,
    },
  ],
  Shawarma: [
    {
      code: 999,
      modifierGroups: [{}],
      indexInCategory: 99,
      _id: "6216883d03c711507b81cbe8",
      category: "Shawarma",
      printName: "8PC Chicken",
      popular: false,
      video: "",
      archived: false,
      price: 430,
      onSale: true,
      isAvailable: true,
      image: null,
      description: "Chicken wings with beautiful crush of shits and molicuts",
      name: "8 pc Chicken wings",
      __v: 0,
    },
    {
      code: 999,
      modifierGroups: [{}],
      indexInCategory: 99,
      _id: "62169212006303488d067aa4",
      category: "Shawarma",
      printName: "",
      popular: false,
      video: "",
      archived: false,
      price: 120,
      onSale: true,
      isAvailable: true,
      image: null,
      description: "showrman flavoured with chcobar tasky blendy",
      name: "Chocolator Amuco shawarmo",
      __v: 0,
    },
  ],
  chicken: [
    {
      code: 999,
      modifierGroups: [{}],
      indexInCategory: 99,
      _id: "620872b2586ea1c3df27940d",
      category: "chicken",
      popular: false,
      video: null,
      archived: false,
      price: 33,
      onSale: true,
      isAvailable: true,
      image:
        "https://image.shutterstock.com/image-photo/refreshing-summer-mojito-cocktail-ice-600w-1937744053.jpg",
      description: "amul treety",
      name: "Amazing truthy",
      __v: 0,
    },
    {
      code: 999,
      modifierGroups: [{}],
      indexInCategory: 99,
      _id: "620872bd586ea1c3df27940f",
      category: "chicken",
      popular: false,
      video: null,
      archived: false,
      price: 33,
      onSale: true,
      isAvailable: true,
      image: null,
      description: "amul treety",
      name: "Tuman truthy",
      __v: 0,
    },
    {
      code: 999,
      modifierGroups: [{}],
      indexInCategory: 99,
      _id: "620872c3586ea1c3df279411",
      category: "chicken",
      popular: false,
      video: null,
      archived: false,
      price: 33,
      onSale: true,
      isAvailable: true,
      image: null,
      description: "amul treety",
      name: "Algoo truthy",
      __v: 0,
    },
    {
      code: 999,
      modifierGroups: [{}],
      indexInCategory: 99,
      _id: "620872cb586ea1c3df279413",
      category: "chicken",
      popular: false,
      video: null,
      archived: false,
      price: 33,
      onSale: true,
      isAvailable: true,
      image: null,
      description: "amul treety",
      name: "Smookoo truthy",
      __v: 0,
    },
    {
      code: 999,
      modifierGroups: [{}],
      indexInCategory: 99,
      _id: "620882d8f6ff15ae1d5b29c6",
      category: "chicken",
      popular: false,
      video: null,
      archived: false,
      price: 55,
      onSale: true,
      isAvailable: true,
      image: null,
      description: "kundy kidddd",
      name: "Dubakoo chicken blha",
      __v: 0,
    },
  ],
  juice: [
    {
      code: 999,
      indexInCategory: 99,
      _id: "6208726b586ea1c3df27940b",
      category: "juice",
      popular: false,
      video: null,
      archived: false,
      price: 33,
      onSale: true,
      isAvailable: true,
      image: null,
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla elit nulla, cursus id libero nec, tempor tempor leo. Integer ut posuere felis, sed pretium ante. Nulla vehicula, nisl laoreet molestie ultrices, turpis nunc efficitur libero, eu pharetra felis arcu ut ipsum. Nulla accumsan molestie venenatis. Suspendisse potenti. Aenean sit amet eros eget nunc consectetur luctus. Nullam mollis orci ac nibh rhoncus hendrerit. Sed vel tempus justo, vel commodo diam. Praesent sed tristique sem. Donec varius est quam. Vivamus a metus vulputate, tempor odio et, hendrerit nulla. Fusce orci turpis, interdum in nibh ullamcorper, venenatis rhoncus eros. Proin rutrum posuere malesuada. Curabitur dignissim quis nisl at tincidunt. Curabitur at nunc ac erat congue bibendum vitae vitae justo.\n\nCurabitur nec elementum lacus, id tincidunt dolor. Fusce vitae nunc ligula. Phasellus ut consectetur ex, scelerisque bibendum odio. Vestibulum ac eros quis magna elementum posuere eget ac quam. Nullam semper ante quis quam facilisis euismod. Integer est tortor, commodo vitae mattis vehicula, tristique tempor tortor. In non neque pretium, elementum nunc at, eleifend diam. Donec varius quis mi vel elementum.",
      name: "truppy truthy",
      __v: 0,
      modifierGroups: [
        {
          description: "Choose Milk ",
          modifiers: [
            { description: "Full Fat Amul Milk", price: "30", id: "1" },
            { description: "Skirmed Milk Amul", price: "15", id: "2" },
          ],
        },
        {
          description: "Select Lattuce Option",
          modifiers: [
            { description: "green lattuce", price: "14" },
            { description: "Green Lattuce", price: "22" },
          ],
        },
      ],
    },
    {
      code: 999,
      modifierGroups: [{}],
      indexInCategory: 99,
      _id: "620872d6586ea1c3df279415",
      category: "juice",
      popular: false,
      video: null,
      archived: false,
      price: 33,
      onSale: true,
      isAvailable: true,
      image: null,
      description: "amul treety",
      name: "Creepy crop truthy",
      __v: 0,
    },
    {
      code: 999,
      modifierGroups: [{}],
      indexInCategory: 99,
      _id: "620872db586ea1c3df279417",
      category: "juice",
      popular: false,
      video: null,
      archived: false,
      price: 33,
      onSale: true,
      isAvailable: true,
      image: null,
      description: "amul treety",
      name: "algolia crop truthy",
      __v: 0,
    },
    {
      code: 999,
      modifierGroups: [{}],
      indexInCategory: 99,
      _id: "620872e3586ea1c3df279419",
      category: "juice",
      popular: false,
      video: null,
      archived: false,
      price: 33,
      onSale: true,
      isAvailable: true,
      image:
        "https://media.istockphoto.com/photos/red-cocktail-on-the-rocks-with-mint-leaf-and-lime-peal-picture-id1307922429?s=612x612",
      description: "amul treety",
      name: "brothyeee crop truthy",
      __v: 0,
    },
    {
      code: 999,
      modifierGroups: [{}],
      indexInCategory: 99,
      _id: "620872e9586ea1c3df27941b",
      category: "juice",
      popular: false,
      video: null,
      archived: false,
      price: 33,
      onSale: true,
      isAvailable: true,
      image:
        "https://images.unsplash.com/photo-1595977514600-72cbc8376c38?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
      description: "amul treety",
      name: "cuckhedo crop truthy",
      __v: 0,
    },
  ],
};
